apiVersion: v1
appVersion: 1.5.2
description: A Helm chart for Stratos Metrics
name: metrics
version: 1.1.2
sources:
  - https://github.com/SUSE/stratos-metrics
icon: https://raw.githubusercontent.com/SUSE/stratos-metrics/master/icon.svg
