dependencies:
- name: prometheus
  version: "7.3.6"
  repository: "https://kubernetes-charts.storage.googleapis.com"
- name: grafana
  version: "3.4.0"
  repository: "https://kubernetes-charts.storage.googleapis.com"
  condition: grafana.enabled