---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-stratos-metrics-grafana-datasource"
  labels:
    app.kubernetes.io/name: "stratos-metrics"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "stratos-metrics-{{ .Values.cfName }}-config"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    stratos-metrics-datasource: "prometheus"
data:
  datasource.yaml: |
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: https://{{ .Release.Name }}-{{ .Values.nginx.serviceName }}
      basicAuth: true 
      basicAuthUser: {{ .Values.metrics.username }}
      basicAuthPassword: {{ .Values.metrics.password }}
      isDefault: true
      jsonData:
        tlsSkipVerify: true
      version: 1
      editable: false
