{{- if and .Values.kube.registry.username .Values.kube.registry.password }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockercfg
metadata:
  name: {{ .Values.dockerRegistrySecret }}
  labels:
    app.kubernetes.io/name: "stratos-metrics"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "console-metrics-dockerreg-secret"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  .dockercfg: {{ template "imagePullSecret" . }}
{{- end}}
