{{- if and .Values.kube.registry.username .Values.kube.registry.password }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockercfg
metadata:
  name: {{ .Values.dockerRegistrySecret }}
  labels:
    app.kubernetes.io/name: "stratos-metrics"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "console-metrics-dockerreg-secret"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  .dockercfg: {{ template "imagePullSecret" . }}
{{- end}}
{{- if not .Values.nginx.tls }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-nginx-tls"
type: Opaque
data:
  cert.crt: {{ .Values.nginx.ssl.cert | b64enc }}
  cert.key: {{ .Values.nginx.ssl.certKey | b64enc }}
{{- end}}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-metrics-credentials"
type: Opaque
data:
  username: {{ template "nginx.credentials-username-base64" . }}
  password: {{ template "nginx.credentials-password-base64" . }}